[package]
name = "torc-slurm-job-runner"
version = "0.7.0"
edition = "2024"

[dependencies]
torc = { path = ".." }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.1"
log = "0.4"
chrono = "0.4.38"
hostname = "0.4.0"
serde_json.workspace = true
signal-hook.workspace = true
